### ISSUE TITLE
Let privileged users view information about non-published papers

### ISSUE THREAD

**Issue by TobiasKappe** [CCSDForge/episciences-api#11]
Currently, when issuing a request to `/api/papers`, all that comes up are papers with a status of 16, i.e., "published". When requesting a paper via `/api/papers/{docid}` that is not yet published, a 404 error is returned.

For LMCS's tooling to work, we also need to have information about papers with different statuses. For instance, we need to know which papers are currently marked as "accepted".

Would it be possible to extend the output of `/api/papers` to include all papers that are visible to the user currently logged in, including those that are not yet published?

**Comment by rtournoy** [comment]
Thanks for the report, it should have been fixed with latest version
