### ISSUE TITLE
Error 500 when logging into preproduction API

### ISSUE THREAD

**Issue by TobiasKappe** [CCSDForge/episciences-api#31]
When I try to log into the pre-production API at https://api-preprod.episciences.org, I get an error 500 when supplying the correct credentials.

To reproduce:
```
curl -X 'POST' \
  'https://api-preprod.episciences.org/api/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "<username>",
  "password": "<correct api token>",
  "code": "epijinfo.episciences.org"
}'
```

When I supply an _incorrect_ API token, I get an error 401.

Logging in via the production instance at https://api.episciences.org seems to work just fine.

**Comment by rtournoy** [comment]
We have fixed the issue (the database for pre-production was missing an update, but the production was up to date).

 :warning: About `"code": "epijinfo.episciences.org"` you have to use only the journal's code : `"code": "epijinfo"`
the part of the string before `.episciences.org`. We will update the examples in the documentation to avoid confusion

**Comment by TobiasKappe** [comment]
Fantastic, thanks for looking into this!
